#Consider all integer combinations of ab for 2 <= a <= 5 and 2 <= b <= 5:

#2**2=4, 2**3=8, 2**4=16, 2**5=32
#3**2=9, 3**3=27, 3**4=81, 3**5=243
#4**2=16, 4**3=64, 44=256, 45=1024
#5**2=25, 5**3=125, 5**4=625, 5**5=3125
#If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

#4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

#How many distinct terms are in the sequence generated by ab for 2 <= a <= 100 and 2 <= b <= 100?

#create a, a list of integers 2-100
a = list(range(2,101))
#create an empty list to add numbers that fill conditions to
sequence = []
#cycle through every number in a for every number of a
for x in a:
    for y in a:
        #add the result of the first number to the power of the second number to the 'sequence' list
        sequence.append(x**y)
#change the list into a set to remove duplicate results, then change it back to a list.
sequence = list(set(sequence))
#print the length of the 'sequence' list
print len(sequence)
